config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      current_user.update_last_seen
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
      @users = User.all
    end
  end

  def help
    if logged_in?
      current_user.update_last_seen
    end
  end

  def about
    if logged_in?
      current_user.update_last_seen
    end
  end

  def contact
    if logged_in?
      current_user.update_last_seen
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="well">
  <h1 id="coolify-title">About</h1>
  <p>
    Hello, and thanks for visiting! Poppin is my version of the Sample App from 
    Michael Hartl's
    <a href="http://www.railstutorial.org/" target="_blank"><em>Ruby on Rails
    Tutorial</em></a>. I created Poppin in March 2016 as a project for Robeen Dey's 
    <a href="https://codermanual.com/" target="_blank">Coder Manual</a> coding 
    bootcamp. I highly recommend these resources to anyone looking to learn 
    web development.
  </p>
  
  <p>
    There are a few rules I'd like you to follow to keep Poppin fun for everyone:
  </p>
  <ol>
    <li>No profanity</li>
    <li>No obscene profile images, language, etc.</li>
    <li>No spamming, trolling, etc.</li>
    <li>Above all, be nice to each other (please)</li>
  </ol>
  <p>
    If I see anything that could cause a disturbance of the peace, I'll give a 
    warning to the person(s) involved and do my best to try to solve the 
    problem. If the behavior continues, I may have to delete the problematic 
    Pops (or even the entire accounts involved). If it somehow persists after 
    that, I will send a note home to your parents and put you in the corner 
    for a time-out.
  </p>
  
  <p>
    Anyways, just don't Pop anything you wouldn't want Mom, the Pentagon, or 
    Jesus to see. Besides, all moms have mother's intuition (and can tell when 
    you're getting into trouble), the Pentagon is probably monitoring 
    your Pops right now, and Jesus is, well, omniscient (to say the least).
  </p>
  
  <p>
    Special thanks to users 
    <a href="https://warm-temple-79460.herokuapp.com/users/102" target="_blank">Sydney Barta</a>,
    <a href="https://warm-temple-79460.herokuapp.com/users/103" target="_blank">Gabriela</a>,
    <a href="https://warm-temple-79460.herokuapp.com/users/104" target="_blank">ginna_rosie</a>,
    and 
    <a href="https://warm-temple-79460.herokuapp.com/users/109" target="_blank">Joshua Newton</a>
    for their awesome theme ideas, and to user 
    <a href="https://warm-temple-79460.herokuapp.com/users/111" target="_blank">Kiara</a> for 
    the awesome 
    <a href="http://kakaunolakouiailalo.blogspot.com/2016/03/poppin.html" target="_blank">write-up!</a> 
    Check out her blog 
    <a href="http://kakaunolakouiailalo.blogspot.com" target="_blank">here</a>.
  </p>
  <p>
    <i>
      Tyler Acosta is a Catholic, a 
      <a href="https://www.youtube.com/channel/UCoCUaN6pEJ5i09_zbhR8uYQ" target="_blank">musician</a>, 
      an aspiring web developer, 
      a homeschooler, and a tennis player in Springfield, Missouri. He enjoys 
      popcorn, playing piano/melodica/keytar/anything that has keys, 
      rollerblading, and a lot of other things too. If you've logged in, you 
      can check out his Kernel 
      <a href="https://warm-temple-79460.herokuapp.com/users/101">here</a>.
    </i>
  </p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="well">
  <h1 id="coolify-title">Contact</h1>
  <p>
    Send all your questions, comments, suggestions, monies, etc. to Tyler Acosta at 
    <a href="mailto:tacos1998@gmail.com">tacos1998@gmail.com</a>.
  </p>
  
  <p>
    In addition to being a web developer. Tyler is also a 
    <a href="https://www.gigsalad.com/tyler_acosta_springfield" target="_blank">performing</a> 
    <a href="https://www.youtube.com/channel/UCoCUaN6pEJ5i09_zbhR8uYQ" target="_blank">musician</a>, 
    competitive tennis player, and rigorous scholar, who needs all the cash he 
    can get to save for college. Please contact him using the 
    above email address for gig/booking inquiries, 
    music lesson info (piano/recording software training), tennis lesson info, 
    racquet stringing services, tutoring, and any other work/performance 
    opportunities.
  </p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="well">
  <h1 id="coolify-title">Help</h1>
  <h2>
    <a href="https://youtu.be/5kHQ0AhkDnU?t=6" target="_blank">(I need somebody!)</a>
  </h2>
  
  <p>
    To get started with Poppin, visit 
    the <%= link_to "signup page", new_user_path %> 
    and create your account. You should recieve a confirmation email that 
    contains your activation link. Click on the link and you'll be directed to 
    your Kernel.
  </p>
  
  <p>
    Poppin uses <a href="https://en.gravatar.com/" target="_blank">Gravatar</a> to manage 
    profile pictures. Simply create a Gravatar/Wordpress account with your email 
    (the same one you use with Poppin), link an image, 
    and <i><strong>voila!</strong></i> 
    Poppin automagically updates your account with the picture!
  </p>
  
  <p>
    Your Kernel is your profile page. It displays your name, Gravatar, and all 
    of your Pops, along with a button at the top for people to Crunch or 
    Uncrunch you. This is what other users will see when they click on you. 
    Once you've logged in, you can view your Kernel by clicking the 
    "My Kernel" link in the navbar's Account dropdown menu (top right corner).
  </p>
  
  <p>
    Your Pop Box can be accessed by clicking the Poppin logo (top left corner) 
    or the "Home" link in the navbar once you've logged in. This is where you 
    can Pop and view a feed of Pops from yourself and from the users you're 
    crunching. Pops are limited to 200 characters.
  </p>
  
  <p>
    If you find a Pop from another user that you particularly enjoy, you 
    should Savor it! Just hit that Savor button and that Pop's Savor count will 
    increase.
  </p>
  
  <p>
    Everything else should be pretty self-explanatory. You kids are all 
    obsessed with your TwitBookStagrams these days, so I'm sure you already 
    know the drill.
  </p>

  <p>
    If you have any questions, comments, feedback, suggestions, or bugs to 
    report, please contact the admin at 
    <a href="mailto:tacos1998@gmail.com">tacos1998@gmail.com</a> for assistance.
  </p>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="well row main">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="well col-md-8">
      <h3 id="popbox">Pop Box <%= render 'shared/now_playing' %></h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1 id="coolify">POPPIN</h1>

    <h2>
      Pop your thoughts. Crunch your friends. Add salt to taste.
    </h2>

    <%= link_to "Let's get Poppin!", login_path, class: "btn btn-lg btn-primary" %>
  </div>

  <!-- <%= link_to image_tag("rails.png", alt: "Rails logo"),
              'http://rubyonrails.org/' %> -->
<% end %>