config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :logged_in_user
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]
  before_action :update_last_seen_timestamp

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def show
    @conversation.mark_as_read(current_user)
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.erb
<div class="panel panel-default clearfix">
  <div class="panel-heading">
    <%= render 'conversations/participants', conversation: conversation %>
    <h5 id="convo-title"><%= link_to conversation.subject, conversation_path(conversation), class: 'convo-sub' %></h5>
  </div>
  
  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info restore-only', method: :post %>
    <% else %>
      <% if conversation.is_unread?(current_user) %>
        <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                  data: {confirm: 'Are you sure?'} %>
        <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                    class: 'btn btn-xs btn-info', method: :post %>
      <% else %>
        <%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger trash-only', method: :delete,
                  data: {confirm: 'Are you sure?'} %>
      <% end %>
    <% end %>
  </div>

  
  <div class="panel-body">
    <p id="convo-info convo-title"><%= conversation.last_message.body %>
      <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small>
      <br><%= link_to conversation.last_message.sender.name, user_path(conversation.last_message.sender.id), method: :get, target: '_blank' %>
    </p>
  </div>
</div>

app/views/conversations/_participants.html.erb
<div class="participant-gravatars">
  <% conversation.participants.each do |participant| %>
    <% unless participant == current_user %>
      <% if conversation.participants.count == 2 %>
        <%= link_to gravatar_for(participant, size: 80), participant %>
      <% elsif conversation.participants.count == 3 %>
        <%= link_to gravatar_for(participant, size: 40), participant %>
      <% else %>
        <%= link_to gravatar_for(participant, size: 40), participant %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/conversations/index.html.erb
<div class="well">
  <div class="center">
    <h1 id="coolify-title">My Nibbles</h1>
    <%= link_to 'Create a new Nibble', new_message_path, class: 'btn btn-md btn-primary nibble-btn-inbox' %>
  </div>
  
  <div class="row">
    <div class="col-sm-3">
      <ul class="nav nav-pills nav-stacked">
        <%= mailbox_section 'inbox', @box %>
        <%= mailbox_section 'sent', @box %>
        <%= mailbox_section 'trash', @box %>
      </ul>
    </div>
  
    <div class="col-sm-9">
      <% if @conversations.any? %>
        <% if @box == 'trash' %>
          <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
                         data: {confirm: 'Are you sure?'} %></p>
        <% end %>
        <ul class="list-group">
          <%= render partial: 'conversations/conversation', collection: @conversations %>
        </ul>
      
        <%= will_paginate %>
      <% else %>
        <div class="well">
          <h1>This mailbox is empty.</h1>
          <h2>Move along, nothing to see here.</h2>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="well">
  <h1 id="coolify-title">Nibble</h1>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= render 'conversations/participants', conversation: @conversation %>
      <h5 id="convo-title"><%= @conversation.subject %></h5>
    </div>
    <div class="panel-body">
      <div>
        <% @conversation.receipts_for(current_user).each do |receipt| %>
          <p>
            <% message = receipt.message %>
    
            <%= message.body %> - 
            <%= link_to message.sender.name, user_path(message.sender.id), method: :get, target: '_blank' %> 
            (<%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %>)
          </p>
        <% end %>
      </div>
    </div>
  </div>
  
  <%= form_tag reply_conversation_path(@conversation), method: :post do %>
    <div class="form-group">
      <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
    </div>
    <%= submit_tag "Nibble it!", class: 'btn btn-primary' %>
  <% end %>

</div>

<script>
  $(function(){
    data = <%= raw User.pluck(:name).compact.to_json %>;
    $('textarea').atwho({at:"@", 'data':data });
});
</script>