config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_favicon.html.erb
<!-- table favicon until I can test on multiple devices -->
<!--<# %w(76 120 152 180).each do |size| %>
  <#= favicon_link_tag "apple-touch-icon-#{size}x#{size}.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<# end %>

<# %w(16 32).each do |size| %>
  <#= favicon_link_tag "favicon-#{size}x#{size}.png", rel: 'icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<# end %>-->

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts" id="refreshable">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items, id: "home-pagination" %>
<% else %>
  <h1>Well, this is awkward...</h1>
  <h2>There's nothing to display here. A couple suggestions:</h2>
  <h2>1. Use the textbox on this page to start Poppin</h2>
  <h2>2. Head over to <%= link_to "The Popper", users_path %> and crunch some Kernels</h2>
<% end %>

<!--make feed refreshable -->
<script>
  setInterval( function() {
    $("#refreshable").load(location.href+" #refreshable>*", "");
  }, 30000);
</script>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "What's poppin?", maxLength: 200 %>
  </div>
  <span id="chars">200 characters remaining</span>
  <%= f.submit "Pop it!", class: "btn btn-primary" %>
  <!-- <span class="picture">
    <%# f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span> %> -->
<% end %>

<!-- <script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script> -->

<script type="text/javascript">
  var maxLength = 200;
  $('textarea').keyup(function() {
    var length = $(this).val().length;
    var string = " characters remaining"
    var length = maxLength-length+string;
    $('#chars').text(length);
  });
</script>

<script>
  $(function(){
    data = <%= raw User.pluck(:name).compact.to_json %>;
    $('textarea').atwho({at:"@", 'data':data });
});
</script>

app/views/shared/_now_playing.html.erb
<div class="btn-group now-playing">
  <button type="button" class="btn btn-xs btn-default dropdown-toggle" id="now-playing-btn" data-toggle="dropdown" data-target="#" aria-haspopup="true" aria-expanded="false">
    Now Playing
    <span class="caret"></span>
  </button>
  <div class="user_avatars_savor dropdown-menu dropdown-menu-form" aria-labelledby="dropdownMenu2">
    <% User.all.each do |user| %>
      <% if user.last_seen? && user.last_seen > 10.minutes.ago %>
        <%= link_to gravatar_for(user, size: 30), user %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following red-hover" class="stat">
      <%= @user.following.count %>
    </strong>
    crunching
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers blue-hover" class="stat">
      <%= @user.followers.count %>
    </strong>
    crunchers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 55), current_user %>
<h1 id="coolify-title"><%= current_user.name %></h1>
<span><%= link_to "view my Kernel", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "pop") %></span>